### Site Settings ###
title               : Cheedella Vamsi Kishore
description         : >- 
                      From Robotics to finance and exploring the world, I wear many hats. 🎩📊🎥✈️ Join me in conversations about math, Finance, cinema and travel. 🤖🌎
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : vamsi1961/vamsi1961.github.io   # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : udaygirish/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/testblog.md
  - pages/fquotes.md
  - pages/status.md
  - pages/contact.md
  - pages/projects.html

#  - pages/contact.html

### Author Info ###
author:
  name              : Cheedella Vamsi Kishore
  image             : ./assets/kishore.jpg
# behance           : your_username
# dribbble          : your_username
  email             : cheedellavamsikishore@gmail.com
# facebook          : your_username
  github            : vamsi1961
# gitlab            : your_username
  instagram         : kishore__1961
  kaggle            : cheedellakishore
  linkedin          : cheedella-vamsi-kishore
  medium            : cheedellavamsikishore
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : cheedella_vamsi
# vimeo             : your_username
  youtube           : CheedellaVamsikishore
#  quora             : Uday-Girish-Maradana
  resume            : Vamsi_Resume.pdf
# cv                : manoj_cv.pdf


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###                        
disqus:        # Your website Shortname on disqus
  shortname: https-vamsi1961-github-io  

### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-175164060-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                  # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "skills"
    values:
      comments: false 

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
